from __future__ import annotations

from app.models import IssueContext, Stage, StageResult, StageStatus


class MockAgentAdapter:
    async def run_stage(self, stage: Stage, context: IssueContext) -> StageResult:
        issue_key = context.issue_id.lower()

        if "force-fail" in issue_key:
            return StageResult(
                status=StageStatus.FAILED,
                summary=f"Mock {stage.value} failed by issue key token.",
            )

        if stage == Stage.DESIGN:
            return StageResult(
                status=StageStatus.SUCCESS,
                summary="Claude(Mock): 产出实现方案、边界条件与验收点。",
                artifacts={"design_doc": "MVP plan generated by mock"},
            )

        if stage == Stage.CODING:
            attempt = context.attempts.get(stage.value, 0)
            if "flaky-coding" in issue_key and attempt == 0:
                return StageResult(
                    status=StageStatus.FAILED,
                    summary="Codex(Mock): 首次编码失败，用于验证重试。",
                )
            branch = context.branch or f"plane/{context.issue_id}-mock"
            return StageResult(
                status=StageStatus.SUCCESS,
                summary="Codex(Mock): 完成编码并准备 PR。",
                artifacts={"branch": branch, "commit": "mock-commit-sha"},
            )

        if stage == Stage.REVIEW:
            if "needs-changes" in issue_key and context.review_loops == 0:
                return StageResult(
                    status=StageStatus.NEEDS_CHANGES,
                    summary="Gemini(Mock): 需要调整命名与风格。",
                )
            return StageResult(
                status=StageStatus.SUCCESS,
                summary="Gemini(Mock): 代码通过规范与风格审查。",
                artifacts={"review": "approved"},
            )

        return StageResult(status=StageStatus.FAILED, summary="Unknown stage")

